// Complete 69-Laptop Real Inventory Dataset
const LAPTOPS_INVENTORY = [
  {
    "id": 1,
    "name": "LENOVO T14G1 Core i7 10Th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad T14",
    "cpu": "Intel Core i7-10610U 10th Gen",
    "cpuTag": "intel_i7",
    "gen": "10th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Corporate Ultrabook",
    "badge": "Best Seller",
    "badgeType": "b-corp",
    "price": 98000,
    "priceFormatted": "Rs 98,000",
    "priceUsd": 350,
    "img": "images/laptop-1-lenovo-thinkpad-t14-1.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 2,
    "name": "Surface Tab 1866 Core i5 10th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Pro 7",
    "cpu": "Intel Core i5-1035G4 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "12.3\" PixelSense (2736x1824) Touch",
    "gpu": "Intel Iris Plus Graphics",
    "gpuType": "integrated",
    "category": "2-in-1 Tablet PC",
    "badge": "Touch & Pen",
    "badgeType": "b-val",
    "price": 88000,
    "priceFormatted": "Rs 88,000",
    "priceUsd": 315,
    "img": "images/laptop-2-microsoft-surface-pro-7-2.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "creator"
    ]
  },
  {
    "id": 3,
    "name": "HP EliteBook 840G9 Core i5/i7 12th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 840 G9",
    "cpu": "Intel Core i7-1255U 12th Gen (10-Core)",
    "cpuTag": "intel_i7",
    "gen": "12th",
    "ram": 16,
    "storage": 512,
    "display": "14\" WUXGA 16:10 IPS 400 nits",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Executive Ultrabook",
    "badge": "Newer Gen",
    "badgeType": "b-gen",
    "price": 165000,
    "priceFormatted": "Rs 165,000",
    "priceUsd": 590,
    "img": "images/laptop-3-hp-elitebook-840-g9-3.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "creator"
    ]
  },
  {
    "id": 4,
    "name": "Lenovo X1 Yoga Core i5 12th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad X1 Yoga Gen 7",
    "cpu": "Intel Core i5-1240P 12th Gen (12-Core)",
    "cpuTag": "intel_i5",
    "gen": "12th",
    "ram": 16,
    "storage": 512,
    "display": "14\" WUXGA Touch 360\u00b0 with Stylus",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Flagship 2-in-1",
    "badge": "360\u00b0 Touch",
    "badgeType": "b-val",
    "price": 185000,
    "priceFormatted": "Rs 185,000",
    "priceUsd": 660,
    "img": "images/laptop-4-lenovo-thinkpad-x1-yoga-gen-7-4.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "creator",
      "programming"
    ]
  },
  {
    "id": 5,
    "name": "Lenovo X13 Core i5 10th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad X13 Gen 1",
    "cpu": "Intel Core i5-10210U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 16,
    "storage": 256,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Ultra-Portable Business",
    "badge": "Compact",
    "badgeType": "b-corp",
    "price": 82000,
    "priceFormatted": "Rs 82,000",
    "priceUsd": 295,
    "img": "images/laptop-5-lenovo-thinkpad-x13-gen-1-5.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 6,
    "name": "Lenovo T14G1 Ryzen 7 Pro",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad T14 Gen 1",
    "cpu": "AMD Ryzen 7 PRO 4750U 8-Core/16-Thread",
    "cpuTag": "amd",
    "gen": "Ryzen 4000",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "AMD Radeon Vega 7",
    "gpuType": "integrated",
    "category": "8-Core Workhorse",
    "badge": "Heavy Dev",
    "badgeType": "b-corp",
    "price": 105000,
    "priceFormatted": "Rs 105,000",
    "priceUsd": 375,
    "img": "images/laptop-6-lenovo-thinkpad-t14-gen-1-6.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "programming",
      "office",
      "student"
    ]
  },
  {
    "id": 7,
    "name": "Lenovo 13 Core i5 6th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad 13 Gen 1",
    "cpu": "Intel Core i5-6200U 6th Gen",
    "cpuTag": "intel_i5",
    "gen": "6th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" HD Anti-Glare",
    "gpu": "Intel HD Graphics 520",
    "gpuType": "integrated",
    "category": "Budget Student",
    "badge": "Under 50k",
    "badgeType": "b-val",
    "price": 44000,
    "priceFormatted": "Rs 44,000",
    "priceUsd": 160,
    "img": "images/laptop-7-lenovo-thinkpad-13-gen-1-7.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 8,
    "name": "Dell XPS 15 Core i7 6th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "XPS 15 9550",
    "cpu": "Intel Core i7-6700HQ Quad Core 45W",
    "cpuTag": "intel_i7",
    "gen": "6th",
    "ram": 16,
    "storage": 512,
    "display": "15.6\" 4K UHD Touch InfinityEdge",
    "gpu": "NVIDIA GeForce GTX 960M 2GB",
    "gpuType": "discrete",
    "category": "Studio Performance",
    "badge": "4K Touch",
    "badgeType": "b-val",
    "price": 88000,
    "priceFormatted": "Rs 88,000",
    "priceUsd": 315,
    "img": "images/laptop-8-dell-xps-15-9550-8.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "gaming"
    ]
  },
  {
    "id": 9,
    "name": "Dell 5310 Core i5 10th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5310",
    "cpu": "Intel Core i5-10210U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 16,
    "storage": 256,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Compact Business",
    "badge": "Popular",
    "badgeType": "b-corp",
    "price": 78000,
    "priceFormatted": "Rs 78,000",
    "priceUsd": 280,
    "img": "images/laptop-9-dell-latitude-5310-9.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 10,
    "name": "HP 1030G8 Core i7 11th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook x360 1030 G8",
    "cpu": "Intel Core i7-1165G7 11th Gen",
    "cpuTag": "intel_i7",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Touch 360\u00b0 SureView",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Executive 2-in-1",
    "badge": "Premium Touch",
    "badgeType": "b-gen",
    "price": 138000,
    "priceFormatted": "Rs 138,000",
    "priceUsd": 495,
    "img": "images/laptop-10-hp-elitebook-x360-1030-g8-10.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "creator",
      "programming"
    ]
  },
  {
    "id": 11,
    "name": "Dell 5320 Core i5 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5320",
    "cpu": "Intel Core i5-1145G7 vPro 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Corporate Ultrabook",
    "badge": "Top Value",
    "badgeType": "b-corp",
    "price": 92000,
    "priceFormatted": "Rs 92,000",
    "priceUsd": 330,
    "img": "images/laptop-11-dell-latitude-5320-11.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 12,
    "name": "HP EliteBook 1030G2 Core i5 7th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook x360 1030 G2",
    "cpu": "Intel Core i5-7200U 7th Gen",
    "cpuTag": "intel_i5",
    "gen": "7th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" FHD Touch 360\u00b0 Aluminum",
    "gpu": "Intel HD Graphics 620",
    "gpuType": "integrated",
    "category": "Budget 2-in-1",
    "badge": "Touch 360\u00b0",
    "badgeType": "b-val",
    "price": 58000,
    "priceFormatted": "Rs 58,000",
    "priceUsd": 210,
    "img": "images/laptop-12-hp-elitebook-x360-1030-g2-12.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 13,
    "name": "Dell 5430 Core i5 12th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5430",
    "cpu": "Intel Core i5-1235U 12th Gen (10-Core)",
    "cpuTag": "intel_i5",
    "gen": "12th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Modern Business",
    "badge": "12th Gen Fast",
    "badgeType": "b-corp",
    "price": 135000,
    "priceFormatted": "Rs 135,000",
    "priceUsd": 485,
    "img": "images/laptop-13-dell-latitude-5430-13.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming"
    ]
  },
  {
    "id": 14,
    "name": "Dell 7420 Core i5 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 7420 Carbon",
    "cpu": "Intel Core i5-1145G7 vPro 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Carbon Chassis",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Carbon Ultrabook",
    "badge": "Hot Seller",
    "badgeType": "b-corp",
    "price": 105000,
    "priceFormatted": "Rs 105,000",
    "priceUsd": 375,
    "img": "images/laptop-14-dell-latitude-7420-carbon-14.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 15,
    "name": "HP 640G1 Core i5 4th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 640 G1",
    "cpu": "Intel Core i5-4200M 4th Gen",
    "cpuTag": "intel_i5",
    "gen": "4th",
    "ram": 8,
    "storage": 256,
    "display": "14\" HD Anti-Glare",
    "gpu": "Intel HD Graphics 4600",
    "gpuType": "integrated",
    "category": "Entry Budget",
    "badge": "Super Budget",
    "badgeType": "b-val",
    "price": 36000,
    "priceFormatted": "Rs 36,000",
    "priceUsd": 130,
    "img": "images/laptop-15-hp-probook-640-g1-15.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 16,
    "name": "HP 630G9 Core i3 12th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 630 G9",
    "cpu": "Intel Core i3-1215U 12th Gen (6-Core)",
    "cpuTag": "intel_i3",
    "gen": "12th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Modern Budget",
    "badge": "6-Core i3",
    "badgeType": "b-gen",
    "price": 88000,
    "priceFormatted": "Rs 88,000",
    "priceUsd": 315,
    "img": "images/laptop-16-hp-probook-630-g9-16.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 17,
    "name": "Lenovo T480s Core i5 8th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad T480s",
    "cpu": "Intel Core i5-8350U Quad-Core vPro",
    "cpuTag": "intel_i5",
    "gen": "8th",
    "ram": 16,
    "storage": 256,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Legendary Slim",
    "badge": "Cult Classic",
    "badgeType": "b-corp",
    "price": 68000,
    "priceFormatted": "Rs 68,000",
    "priceUsd": 245,
    "img": "images/laptop-17-lenovo-thinkpad-t480s-17.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "programming",
      "office",
      "student"
    ]
  },
  {
    "id": 18,
    "name": "HP 9480 Core i5 4th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook Folio 9480m",
    "cpu": "Intel Core i5-4310U 4th Gen",
    "cpuTag": "intel_i5",
    "gen": "4th",
    "ram": 8,
    "storage": 256,
    "display": "14\" HD+ (1600x900) Aluminum",
    "gpu": "Intel HD Graphics 4400",
    "gpuType": "integrated",
    "category": "Aluminum Slim",
    "badge": "Budget",
    "badgeType": "b-val",
    "price": 38000,
    "priceFormatted": "Rs 38,000",
    "priceUsd": 135,
    "img": "images/laptop-18-hp-elitebook-folio-9480m-18.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 19,
    "name": "HP 640G2 Core i3 6th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 640 G2",
    "cpu": "Intel Core i3-6100U 6th Gen",
    "cpuTag": "intel_i3",
    "gen": "6th",
    "ram": 8,
    "storage": 256,
    "display": "14\" HD Anti-Glare",
    "gpu": "Intel HD Graphics 520",
    "gpuType": "integrated",
    "category": "Everyday Office",
    "badge": "Under 40k",
    "badgeType": "b-val",
    "price": 39000,
    "priceFormatted": "Rs 39,000",
    "priceUsd": 140,
    "img": "images/laptop-19-hp-probook-640-g2-19.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 20,
    "name": "Microsoft Surface Laptop Core i5 10th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Laptop 3",
    "cpu": "Intel Core i5-1035G7 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "13.5\" PixelSense 2256x1504 Touch (3:2)",
    "gpu": "Intel Iris Plus Graphics",
    "gpuType": "integrated",
    "category": "Designer Ultrabook",
    "badge": "3:2 Aspect",
    "badgeType": "b-val",
    "price": 115000,
    "priceFormatted": "Rs 115,000",
    "priceUsd": 415,
    "img": "images/laptop-20-microsoft-surface-laptop-3-20.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "creator"
    ]
  },
  {
    "id": 21,
    "name": "Lenovo X1 Extreme Gen 2 Core i7 9th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad X1 Extreme Gen 2",
    "cpu": "Intel Core i7-9750H (6-Core/12-Thread 45W)",
    "cpuTag": "intel_i7",
    "gen": "9th",
    "ram": 16,
    "storage": 512,
    "display": "15.6\" FHD IPS 500 nits HDR",
    "gpu": "NVIDIA GeForce GTX 1650 Max-Q 4GB",
    "gpuType": "discrete",
    "category": "Performance / Dev",
    "badge": "Dedicated GPU",
    "badgeType": "b-corp",
    "price": 165000,
    "priceFormatted": "Rs 165,000",
    "priceUsd": 590,
    "img": "images/laptop-21-lenovo-thinkpad-x1-extreme-gen-2-21.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "programming",
      "creator",
      "gaming"
    ]
  },
  {
    "id": 22,
    "name": "Dell Latitude 7320(2 in 1) Core i5 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 7320 2-in-1",
    "cpu": "Intel Core i5-1145G7 vPro 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD Touch 360\u00b0 Gorilla Glass",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "2-in-1 Convertible",
    "badge": "Touch 360\u00b0",
    "badgeType": "b-corp",
    "price": 115000,
    "priceFormatted": "Rs 115,000",
    "priceUsd": 415,
    "img": "images/laptop-22-dell-latitude-7320-2-in-1-22.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "creator",
      "student"
    ]
  },
  {
    "id": 23,
    "name": "HP EliteBook 840G8 Core i5 11th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 840 G8",
    "cpu": "Intel Core i5-1135G7 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Aluminum Chassis",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Corporate Ultrabook",
    "badge": "Best Seller",
    "badgeType": "b-corp",
    "price": 105000,
    "priceFormatted": "Rs 105,000",
    "priceUsd": 375,
    "img": "images/laptop-23-hp-elitebook-840-g8-23.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 24,
    "name": "HP EliteBook 840G7 Core i5 10th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 840 G7",
    "cpu": "Intel Core i5-10310U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare B&O Audio",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "All-Aluminum Classic",
    "badge": "In Demand",
    "badgeType": "b-corp",
    "price": 88000,
    "priceFormatted": "Rs 88,000",
    "priceUsd": 315,
    "img": "images/laptop-24-hp-elitebook-840-g7-24.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "programming"
    ]
  },
  {
    "id": 25,
    "name": "Dell Precision 5560 Core i9 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Precision 5560 Workstation",
    "cpu": "Intel Core i9-11950H (8-Core/16-Thread up to 5.0GHz)",
    "cpuTag": "intel_i9",
    "gen": "11th",
    "ram": 32,
    "storage": 1000,
    "display": "15.6\" UHD+ 4K (3840x2400) 500-nit Touch",
    "gpu": "NVIDIA RTX A2000 4GB GDDR6",
    "gpuType": "rtx",
    "category": "Heavy Workstation",
    "badge": "Core i9 Beast",
    "badgeType": "b-game",
    "price": 285000,
    "priceFormatted": "Rs 285,000",
    "priceUsd": 1020,
    "img": "images/laptop-25-dell-precision-5560-workstation-25.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "gaming"
    ]
  },
  {
    "id": 26,
    "name": "Dell XPS 15 9575 Core i7 8th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "XPS 15 9575 2-in-1",
    "cpu": "Intel Core i7-8705G with Radeon RX Vega M",
    "cpuTag": "intel_i7",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "15.6\" 4K UHD Touch 360\u00b0 Convertible",
    "gpu": "Radeon RX Vega M GL 4GB HBM2",
    "gpuType": "discrete",
    "category": "Creator 2-in-1",
    "badge": "Rare 4K 360\u00b0",
    "badgeType": "b-val",
    "price": 115000,
    "priceFormatted": "Rs 115,000",
    "priceUsd": 415,
    "img": "images/laptop-26-dell-xps-15-9575-2-in-1-26.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "gaming",
      "office"
    ]
  },
  {
    "id": 27,
    "name": "HP EliteBook 1030G4 Core i5 8th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook x360 1030 G4",
    "cpu": "Intel Core i5-8365U Quad Core",
    "cpuTag": "intel_i5",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD Touch 360\u00b0 Privacy Screen",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Executive 2-in-1",
    "badge": "SureView Touch",
    "badgeType": "b-corp",
    "price": 82000,
    "priceFormatted": "Rs 82,000",
    "priceUsd": 295,
    "img": "images/laptop-27-hp-elitebook-x360-1030-g4-27.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 28,
    "name": "Lenovo X13 Gen 4 Core i7 13th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad X13 Gen 4",
    "cpu": "Intel Core i7-1355U 13th Gen (10-Core)",
    "cpuTag": "intel_i7",
    "gen": "13th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" WUXGA 16:10 IPS 400 nits",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Modern Compact",
    "badge": "13th Gen Pro",
    "badgeType": "b-corp",
    "price": 245000,
    "priceFormatted": "Rs 245,000",
    "priceUsd": 880,
    "img": "images/laptop-28-lenovo-thinkpad-x13-gen-4-28.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "creator"
    ]
  },
  {
    "id": 29,
    "name": "Dell VOSTRO 5490 Core i5 10th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Vostro 5490",
    "cpu": "Intel Core i5-10210U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "14\" FHD Anti-Glare LED",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Business Essential",
    "badge": "Reliable",
    "badgeType": "b-corp",
    "price": 78000,
    "priceFormatted": "Rs 78,000",
    "priceUsd": 280,
    "img": "images/laptop-29-dell-vostro-5490-29.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 30,
    "name": "Dell 7490 Core i7 8th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 7490",
    "cpu": "Intel Core i7-8650U Quad-Core vPro",
    "cpuTag": "intel_i7",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Durable Workhorse",
    "badge": "Top Reliability",
    "badgeType": "b-corp",
    "price": 68000,
    "priceFormatted": "Rs 68,000",
    "priceUsd": 245,
    "img": "images/laptop-30-dell-latitude-7490-30.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 31,
    "name": "Dell 3310(2 in 1) Core i5 10th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 3310 2-in-1",
    "cpu": "Intel Core i5-10210U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" FHD Touch 360\u00b0 Rubberized",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Rugged 2-in-1",
    "badge": "Drop Resistant",
    "badgeType": "b-val",
    "price": 62000,
    "priceFormatted": "Rs 62,000",
    "priceUsd": 220,
    "img": "images/laptop-31-dell-latitude-3310-2-in-1-31.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 32,
    "name": "Dell 7270 Core i5 6th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude E7270",
    "cpu": "Intel Core i5-6300U 6th Gen",
    "cpuTag": "intel_i5",
    "gen": "6th",
    "ram": 8,
    "storage": 256,
    "display": "12.5\" HD Anti-Glare Ultra-Portable",
    "gpu": "Intel HD Graphics 520",
    "gpuType": "integrated",
    "category": "Budget Portable",
    "badge": "Under 45k",
    "badgeType": "b-val",
    "price": 42000,
    "priceFormatted": "Rs 42,000",
    "priceUsd": 150,
    "img": "images/laptop-32-dell-latitude-e7270-32.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 33,
    "name": "Dell Latitude 5320 Core i5 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5320",
    "cpu": "Intel Core i5-1145G7 vPro 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS 400 nits Anti-Glare",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Corporate Ultrabook",
    "badge": "High Demand",
    "badgeType": "b-corp",
    "price": 92000,
    "priceFormatted": "Rs 92,000",
    "priceUsd": 330,
    "img": "images/laptop-33-dell-latitude-5320-33.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 34,
    "name": "Lenovo E14 Core i3 10th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad E14 Gen 1",
    "cpu": "Intel Core i3-10110U 10th Gen",
    "cpuTag": "intel_i3",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "14\" FHD Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Budget ThinkPad",
    "badge": "Great Value",
    "badgeType": "b-val",
    "price": 62000,
    "priceFormatted": "Rs 62,000",
    "priceUsd": 220,
    "img": "images/laptop-34-lenovo-thinkpad-e14-gen-1-34.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 35,
    "name": "HP EliteBook 1030G3 Core i5 8th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook x360 1030 G3",
    "cpu": "Intel Core i5-8350U Quad Core",
    "cpuTag": "intel_i5",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Touch 360\u00b0 CNC Aluminum",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Sleek 2-in-1",
    "badge": "B&O Audio",
    "badgeType": "b-val",
    "price": 75000,
    "priceFormatted": "Rs 75,000",
    "priceUsd": 270,
    "img": "images/laptop-35-hp-elitebook-x360-1030-g3-35.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "creator"
    ]
  },
  {
    "id": 36,
    "name": "Dell Alienware M15 R7 Ryzen 7 6800H",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Alienware M15 R7",
    "cpu": "AMD Ryzen 7 6800H (8-Core/16-Thread 4.7GHz)",
    "cpuTag": "amd",
    "gen": "Ryzen 6000",
    "ram": 16,
    "storage": 1000,
    "display": "15.6\" QHD 240Hz 2ms G-SYNC",
    "gpu": "NVIDIA GeForce RTX 3070 Ti 8GB (150W)",
    "gpuType": "rtx",
    "category": "Extreme Gaming",
    "badge": "RTX 3070 Ti",
    "badgeType": "b-game",
    "price": 340000,
    "priceFormatted": "Rs 340,000",
    "priceUsd": 1220,
    "img": "images/laptop-36-dell-alienware-m15-r7-36.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "gaming",
      "creator",
      "programming"
    ]
  },
  {
    "id": 37,
    "name": "HP Notebook 15 Core i5 8th",
    "brand": "hp",
    "brandName": "HP",
    "series": "HP 15-da Series",
    "cpu": "Intel Core i5-8250U Quad Core",
    "cpuTag": "intel_i5",
    "gen": "8th",
    "ram": 8,
    "storage": 256,
    "display": "15.6\" FHD Display with Full NumPad",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Everyday 15.6\"",
    "badge": "Full Numpad",
    "badgeType": "b-val",
    "price": 58000,
    "priceFormatted": "Rs 58,000",
    "priceUsd": 210,
    "img": "images/laptop-37-hp-hp-15-da-series-37.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 38,
    "name": "HP Pavilion Core i5 7th",
    "brand": "hp",
    "brandName": "HP",
    "series": "Pavilion 15",
    "cpu": "Intel Core i5-7200U 7th Gen",
    "cpuTag": "intel_i5",
    "gen": "7th",
    "ram": 8,
    "storage": 256,
    "display": "15.6\" FHD IPS B&O Play Audio",
    "gpu": "Intel HD Graphics 620",
    "gpuType": "integrated",
    "category": "Multimedia 15\"",
    "badge": "Affordable",
    "badgeType": "b-val",
    "price": 55000,
    "priceFormatted": "Rs 55,000",
    "priceUsd": 195,
    "img": "images/laptop-38-hp-pavilion-15-38.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 39,
    "name": "Lenovo YOGA 6 Ryzen 5 7350",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "Yoga 6 13.3\"",
    "cpu": "AMD Ryzen 5 7530U / 7350 (6-Core/12-Thread)",
    "cpuTag": "amd",
    "gen": "Ryzen 7000",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" WUXGA 16:10 Touch 360\u00b0 Denim Fabric",
    "gpu": "AMD Radeon Graphics",
    "gpuType": "integrated",
    "category": "Fabric Luxury 2-in-1",
    "badge": "Denim Cover",
    "badgeType": "b-val",
    "price": 135000,
    "priceFormatted": "Rs 135,000",
    "priceUsd": 485,
    "img": "images/laptop-39-lenovo-yoga-6-13-3-39.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "office",
      "student"
    ]
  },
  {
    "id": 40,
    "name": "HP ProBook 640G7 Core i5 10th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 640 G7",
    "cpu": "Intel Core i5-10210U 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Tough Enterprise",
    "badge": "Reliable",
    "badgeType": "b-corp",
    "price": 82000,
    "priceFormatted": "Rs 82,000",
    "priceUsd": 295,
    "img": "images/laptop-40-hp-probook-640-g7-40.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 41,
    "name": "Lenovo YOGA Core i7 12th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "Yoga 7i Gen 7",
    "cpu": "Intel Core i7-1260P 12th Gen (12-Core)",
    "cpuTag": "intel_i7",
    "gen": "12th",
    "ram": 16,
    "storage": 1000,
    "display": "14\" 2.8K 90Hz OLED Touch 360\u00b0",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Luxury OLED 2-in-1",
    "badge": "2.8K OLED",
    "badgeType": "b-gen",
    "price": 195000,
    "priceFormatted": "Rs 195,000",
    "priceUsd": 700,
    "img": "images/laptop-41-lenovo-yoga-7i-gen-7-41.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "office",
      "programming"
    ]
  },
  {
    "id": 42,
    "name": "HP EliteBook 1040G5 Core i7 7th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 1040 G5",
    "cpu": "Intel Core i7-7600U 7th Gen",
    "cpuTag": "intel_i7",
    "gen": "7th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Glass B&O Audio",
    "gpu": "Intel HD Graphics 620",
    "gpuType": "integrated",
    "category": "Executive Slim",
    "badge": "Premium Glass",
    "badgeType": "b-corp",
    "price": 68000,
    "priceFormatted": "Rs 68,000",
    "priceUsd": 245,
    "img": "images/laptop-42-hp-elitebook-1040-g5-42.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 43,
    "name": "Dell Latitude 5310 Core i5 10th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5310 vPro",
    "cpu": "Intel Core i5-10310U vPro 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 16,
    "storage": 256,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Compact Business",
    "badge": "vPro Secure",
    "badgeType": "b-corp",
    "price": 78000,
    "priceFormatted": "Rs 78,000",
    "priceUsd": 280,
    "img": "images/laptop-43-dell-latitude-5310-vpro-43.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 44,
    "name": "HP EliteBook 430G8 Core i3 11th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 430 G8",
    "cpu": "Intel Core i3-1115G4 11th Gen",
    "cpuTag": "intel_i3",
    "gen": "11th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" FHD IPS Ultra-Light",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Ultra-Light Business",
    "badge": "1.28kg Light",
    "badgeType": "b-val",
    "price": 74000,
    "priceFormatted": "Rs 74,000",
    "priceUsd": 265,
    "img": "images/laptop-44-hp-probook-430-g8-44.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 45,
    "name": "Dell Latitude 7320 Core i7 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 7320",
    "cpu": "Intel Core i7-1185G7 vPro (up to 4.8GHz)",
    "cpuTag": "intel_i7",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD Super Low Power 400 nits",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Carbon Ultralight",
    "badge": "Top i7 11th",
    "badgeType": "b-corp",
    "price": 125000,
    "priceFormatted": "Rs 125,000",
    "priceUsd": 450,
    "img": "images/laptop-45-dell-latitude-7320-45.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 46,
    "name": "HP EliteBook 845G7 Ryzen 7 Pro",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 845 G7",
    "cpu": "AMD Ryzen 7 PRO 4750U 8-Core/16-Thread",
    "cpuTag": "amd",
    "gen": "Ryzen 4000",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare B&O Sound",
    "gpu": "AMD Radeon Vega 7",
    "gpuType": "integrated",
    "category": "8-Core Value Beast",
    "badge": "Verified Stock",
    "badgeType": "b-corp",
    "price": 118000,
    "priceFormatted": "Rs 118,000",
    "priceUsd": 425,
    "img": "images/laptop-46-hp-elitebook-845-g7-46.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 47,
    "name": "APPLE MACBOOK M1 PRO 2021",
    "brand": "apple",
    "brandName": "Apple",
    "series": "MacBook Pro 14 (2021)",
    "cpu": "Apple M1 Pro (8-Core CPU / 14-Core GPU)",
    "cpuTag": "apple",
    "gen": "M1 Pro",
    "ram": 16,
    "storage": 512,
    "display": "14.2\" Liquid Retina XDR 120Hz ProMotion",
    "gpu": "Apple 14-Core GPU",
    "gpuType": "apple_gpu",
    "category": "Pro Silicon Creator",
    "badge": "Liquid Retina",
    "badgeType": "b-apple",
    "price": 320000,
    "priceFormatted": "Rs 320,000",
    "priceUsd": 1150,
    "img": "images/laptop-47-apple-macbook-pro-14-2021-47.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "office"
    ]
  },
  {
    "id": 48,
    "name": "HP 1040G1 FOLIO Series Core M5",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook Folio 1040",
    "cpu": "Intel Core M-5Y71 Fanless Ultra-Slim",
    "cpuTag": "intel_i5",
    "gen": "Fanless",
    "ram": 8,
    "storage": 256,
    "display": "12.5\" FHD IPS Aluminum Unibody",
    "gpu": "Intel HD Graphics 5300",
    "gpuType": "integrated",
    "category": "Razor Thin Fanless",
    "badge": "Featherweight",
    "badgeType": "b-val",
    "price": 46000,
    "priceFormatted": "Rs 46,000",
    "priceUsd": 165,
    "img": "images/laptop-48-hp-elitebook-folio-1040-48.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 49,
    "name": "HP EliteBook 630G10 Core i5 13th",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 630 G10",
    "cpu": "Intel Core i5-1335U 13th Gen (10-Core)",
    "cpuTag": "intel_i5",
    "gen": "13th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Anti-Glare Gen 4 NVMe",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "13th Gen Executive",
    "badge": "Gen4 NVMe",
    "badgeType": "b-gen",
    "price": 175000,
    "priceFormatted": "Rs 175,000",
    "priceUsd": 625,
    "img": "images/laptop-49-hp-elitebook-630-g10-49.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming"
    ]
  },
  {
    "id": 50,
    "name": "APPLE MACBOOK PRO 14\" M4 MAX",
    "brand": "apple",
    "brandName": "Apple",
    "series": "MacBook Pro 14 (M4 Max)",
    "cpu": "Apple M4 Max (14-Core CPU / 32-Core GPU)",
    "cpuTag": "apple",
    "gen": "M4 Max",
    "ram": 36,
    "storage": 1000,
    "display": "14.2\" Liquid Retina XDR 1600 nits Nano",
    "gpu": "Apple 32-Core GPU with Ray Tracing",
    "gpuType": "apple_gpu",
    "category": "Ultimate Computing Beast",
    "badge": "Ultra Flagship",
    "badgeType": "b-apple",
    "price": 780000,
    "priceFormatted": "Rs 780,000",
    "priceUsd": 2800,
    "img": "images/laptop-50-apple-macbook-pro-14-m4-max-50.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "gaming"
    ]
  },
  {
    "id": 51,
    "name": "HP X360 Core i7 8th",
    "brand": "hp",
    "brandName": "HP",
    "series": "Envy x360 13",
    "cpu": "Intel Core i7-8550U Quad Core",
    "cpuTag": "intel_i7",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Touch 360\u00b0 Convertible",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Touch 360\u00b0",
    "badge": "Versatile",
    "badgeType": "b-val",
    "price": 85000,
    "priceFormatted": "Rs 85,000",
    "priceUsd": 305,
    "img": "images/laptop-51-hp-envy-x360-13-51.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "creator"
    ]
  },
  {
    "id": 52,
    "name": "HP Spectre X360 Core i7 8th",
    "brand": "hp",
    "brandName": "HP",
    "series": "Spectre x360 13 Gem-Cut",
    "cpu": "Intel Core i7-8565U Quad Core (up to 4.6GHz)",
    "cpuTag": "intel_i7",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" 4K UHD OLED Touch 360\u00b0",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Gem-Cut Luxury",
    "badge": "4K OLED Touch",
    "badgeType": "b-val",
    "price": 98000,
    "priceFormatted": "Rs 98,000",
    "priceUsd": 350,
    "img": "images/laptop-52-hp-spectre-x360-13-gem-cut-52.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "office",
      "student"
    ]
  },
  {
    "id": 53,
    "name": "Microsoft Surface Laptop GO 1943 Core i5 10th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Laptop Go 1943",
    "cpu": "Intel Core i5-1035G1 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "12.4\" PixelSense Touch (3:2) 1.1kg",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Featherweight Touch",
    "badge": "1.1kg Light",
    "badgeType": "b-val",
    "price": 82000,
    "priceFormatted": "Rs 82,000",
    "priceUsd": 295,
    "img": "images/laptop-53-microsoft-surface-laptop-go-1943-53.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "student",
      "office"
    ]
  },
  {
    "id": 54,
    "name": "Lenovo YOGA Slim 7 Core i7 10th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "Yoga Slim 7 14\"",
    "cpu": "Intel Core i7-1065G7 10th Gen (Iris Plus G7)",
    "cpuTag": "intel_i7",
    "gen": "10th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS 100% sRGB 300 nits",
    "gpu": "Intel Iris Plus Graphics",
    "gpuType": "integrated",
    "category": "All-Metal Slim",
    "badge": "100% sRGB",
    "badgeType": "b-corp",
    "price": 125000,
    "priceFormatted": "Rs 125,000",
    "priceUsd": 450,
    "img": "images/laptop-54-lenovo-yoga-slim-7-14-54.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "office",
      "student"
    ]
  },
  {
    "id": 55,
    "name": "HP Spectre X360 Core ULTRA 7",
    "brand": "hp",
    "brandName": "HP",
    "series": "Spectre x360 14 (AI PC)",
    "cpu": "Intel Core Ultra 7 155H (16-Core/22-Thread AI NPU)",
    "cpuTag": "intel_ultra",
    "gen": "Core Ultra",
    "ram": 16,
    "storage": 1000,
    "display": "14\" 2.8K 120Hz OLED Touch 360\u00b0",
    "gpu": "Intel Arc Graphics (Built-in)",
    "gpuType": "integrated",
    "category": "Next-Gen AI Flagship",
    "badge": "Intel Ultra 7",
    "badgeType": "b-gen",
    "price": 395000,
    "priceFormatted": "Rs 395,000",
    "priceUsd": 1420,
    "img": "images/laptop-55-hp-spectre-x360-14-ai-pc-55.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "office"
    ]
  },
  {
    "id": 56,
    "name": "Dell XPS 13 9310 Core i5 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "XPS 13 9310",
    "cpu": "Intel Core i5-1135G7 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.4\" FHD+ 16:10 (1920x1200) 500 nits",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "CNC Aluminum Icon",
    "badge": "500 nits 16:10",
    "badgeType": "b-corp",
    "price": 155000,
    "priceFormatted": "Rs 155,000",
    "priceUsd": 555,
    "img": "images/laptop-56-dell-xps-13-9310-56.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "creator"
    ]
  },
  {
    "id": 57,
    "name": "Lenovo ThinkPad L13 Gen 2 Core i5 11th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad L13 Gen 2",
    "cpu": "Intel Core i5-1135G7 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" FHD IPS Anti-Glare Spill-Resistant",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Rugged Enterprise",
    "badge": "Best Value",
    "badgeType": "b-corp",
    "price": 92000,
    "priceFormatted": "Rs 92,000",
    "priceUsd": 330,
    "img": "images/laptop-57-lenovo-thinkpad-l13-gen-2-57.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 58,
    "name": "Microsoft Surface Laptop 1872 Core i5 10th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Laptop 3 1872",
    "cpu": "Intel Core i5-1035G7 10th Gen",
    "cpuTag": "intel_i5",
    "gen": "10th",
    "ram": 8,
    "storage": 256,
    "display": "13.5\" PixelSense 2256x1504 Touch",
    "gpu": "Intel Iris Plus Graphics",
    "gpuType": "integrated",
    "category": "Alcantara Signature",
    "badge": "PixelSense 3:2",
    "badgeType": "b-val",
    "price": 118000,
    "priceFormatted": "Rs 118,000",
    "priceUsd": 425,
    "img": "images/laptop-58-microsoft-surface-laptop-3-1872-58.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student",
      "creator"
    ]
  },
  {
    "id": 59,
    "name": "HP EliteBook 845G7 Ryzen 5",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 845 G7",
    "cpu": "AMD Ryzen 5 PRO 4650U (6-Core/12-Thread)",
    "cpuTag": "amd",
    "gen": "Ryzen 4000",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare B&O Sound",
    "gpu": "AMD Radeon Vega 6",
    "gpuType": "integrated",
    "category": "6-Core Business",
    "badge": "Top Value",
    "badgeType": "b-corp",
    "price": 98000,
    "priceFormatted": "Rs 98,000",
    "priceUsd": 350,
    "img": "images/laptop-59-hp-elitebook-845-g7-59.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 60,
    "name": "HP ProBook 640G10 Core i5 13th",
    "brand": "hp",
    "brandName": "HP",
    "series": "ProBook 640 G10",
    "cpu": "Intel Core i5-1335U 13th Gen (10-Core)",
    "cpuTag": "intel_i5",
    "gen": "13th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare Gen 4 NVMe",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Enterprise Workhorse",
    "badge": "13th Gen",
    "badgeType": "b-gen",
    "price": 174000,
    "priceFormatted": "Rs 174,000",
    "priceUsd": 625,
    "img": "images/laptop-60-hp-probook-640-g10-60.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming"
    ]
  },
  {
    "id": 61,
    "name": "Dell Latitude 5320 Core i3 11th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 5320",
    "cpu": "Intel Core i3-1125G4 11th Gen (4-Core/8-Thread)",
    "cpuTag": "intel_i3",
    "gen": "11th",
    "ram": 8,
    "storage": 256,
    "display": "13.3\" FHD IPS Anti-Glare",
    "gpu": "Intel UHD Graphics",
    "gpuType": "integrated",
    "category": "Affordable Corporate",
    "badge": "4-Core i3",
    "badgeType": "b-val",
    "price": 75000,
    "priceFormatted": "Rs 75,000",
    "priceUsd": 270,
    "img": "images/laptop-61-dell-latitude-5320-61.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "student"
    ]
  },
  {
    "id": 62,
    "name": "Microsoft Surface Laptop 4 1950 Core i5 11th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Laptop 4 1950",
    "cpu": "Intel Core i5-1135G7 11th Gen",
    "cpuTag": "intel_i5",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.5\" PixelSense 2256x1504 Touch (3:2)",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Modern Surface",
    "badge": "Omnisonic Audio",
    "badgeType": "b-val",
    "price": 145000,
    "priceFormatted": "Rs 145,000",
    "priceUsd": 520,
    "img": "images/laptop-62-microsoft-surface-laptop-4-1950-62.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "creator",
      "student"
    ]
  },
  {
    "id": 63,
    "name": "Microsoft Surface Laptop 4 1979 Core i7 11th",
    "brand": "microsoft",
    "brandName": "Microsoft",
    "series": "Surface Laptop 4 1979",
    "cpu": "Intel Core i7-1185G7 11th Gen",
    "cpuTag": "intel_i7",
    "gen": "11th",
    "ram": 16,
    "storage": 512,
    "display": "13.5\" PixelSense Touch Dolby Atmos",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Executive Surface",
    "badge": "Core i7 Touch",
    "badgeType": "b-val",
    "price": 175000,
    "priceFormatted": "Rs 175,000",
    "priceUsd": 630,
    "img": "images/laptop-63-microsoft-surface-laptop-4-1979-63.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "creator",
      "student"
    ]
  },
  {
    "id": 64,
    "name": "Dell XPS 15 9500 Core i7 10th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "XPS 15 9500",
    "cpu": "Intel Core i7-10750H (6-Core/12-Thread 45W)",
    "cpuTag": "intel_i7",
    "gen": "10th",
    "ram": 16,
    "storage": 512,
    "display": "15.6\" FHD+ 16:10 (1920x1200) 500 nits",
    "gpu": "NVIDIA GeForce GTX 1650 Ti 4GB GDDR6",
    "gpuType": "discrete",
    "category": "Creator Studio 15",
    "badge": "GTX 1650 Ti",
    "badgeType": "b-corp",
    "price": 195000,
    "priceFormatted": "Rs 195,000",
    "priceUsd": 700,
    "img": "images/laptop-64-dell-xps-15-9500-64.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "gaming",
      "programming"
    ]
  },
  {
    "id": 65,
    "name": "Lenovo Thinkpad T490s Core i5 8th",
    "brand": "lenovo",
    "brandName": "Lenovo",
    "series": "ThinkPad T490s",
    "cpu": "Intel Core i5-8365U vPro Quad Core",
    "cpuTag": "intel_i5",
    "gen": "8th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Low Power 400 nits",
    "gpu": "Intel UHD Graphics 620",
    "gpuType": "integrated",
    "category": "Slim Executive",
    "badge": "400 nits Panel",
    "badgeType": "b-corp",
    "price": 78000,
    "priceFormatted": "Rs 78,000",
    "priceUsd": 280,
    "img": "images/laptop-65-lenovo-thinkpad-t490s-65.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "student"
    ]
  },
  {
    "id": 66,
    "name": "APPLE MACBOOK M2 AIR",
    "brand": "apple",
    "brandName": "Apple",
    "series": "MacBook Air M2",
    "cpu": "Apple M2 (8-Core CPU / 8-Core GPU)",
    "cpuTag": "apple",
    "gen": "M2",
    "ram": 16,
    "storage": 512,
    "display": "13.6\" Liquid Retina Display 500 nits",
    "gpu": "Apple 8-Core GPU",
    "gpuType": "apple_gpu",
    "category": "MagSafe Ultra-Thin",
    "badge": "Midnight M2",
    "badgeType": "b-apple",
    "price": 285000,
    "priceFormatted": "Rs 285,000",
    "priceUsd": 1025,
    "img": "images/laptop-66-apple-macbook-air-m2-66.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "office",
      "student",
      "programming"
    ]
  },
  {
    "id": 67,
    "name": "Dell Latitude 7430 Core i7 12th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "Latitude 7430",
    "cpu": "Intel Core i7-1265U 12th Gen (10-Core)",
    "cpuTag": "intel_i7",
    "gen": "12th",
    "ram": 16,
    "storage": 512,
    "display": "14\" FHD IPS Anti-Glare Carbon",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Corporate Ultrabook",
    "badge": "Verified Stock",
    "badgeType": "b-corp",
    "price": 154000,
    "priceFormatted": "Rs 154,000",
    "priceUsd": 550,
    "img": "images/laptop-67-dell-latitude-7430-67.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming"
    ]
  },
  {
    "id": 68,
    "name": "HP EliteBook 630G11 Core ULTA 5",
    "brand": "hp",
    "brandName": "HP",
    "series": "EliteBook 630 G11",
    "cpu": "Intel Core Ultra 5 125U (AI Boost NPU)",
    "cpuTag": "intel_ultra",
    "gen": "Core Ultra",
    "ram": 16,
    "storage": 512,
    "display": "13.3\" WUXGA 16:10 IPS Anti-Glare",
    "gpu": "Intel Graphics",
    "gpuType": "integrated",
    "category": "AI Ultra Workhorse",
    "badge": "Intel Ultra AI",
    "badgeType": "b-gen",
    "price": 215000,
    "priceFormatted": "Rs 215,000",
    "priceUsd": 770,
    "img": "images/laptop-68-hp-elitebook-630-g11-68.jpg",
    "condition": "Like New (10/10) \u00b7 Certified Refurbished",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "office",
      "programming",
      "creator"
    ]
  },
  {
    "id": 69,
    "name": "Dell XPS 9320 Core i7 12th",
    "brand": "dell",
    "brandName": "Dell",
    "series": "XPS 13 Plus 9320",
    "cpu": "Intel Core i7-1280P (14-Core/20-Thread 28W)",
    "cpuTag": "intel_i7",
    "gen": "12th",
    "ram": 16,
    "storage": 512,
    "display": "13.4\" 3.5K OLED Touch or FHD+ 500 nits",
    "gpu": "Intel Iris Xe Graphics",
    "gpuType": "integrated",
    "category": "Invisible Glass Touchpad",
    "badge": "XPS Plus Flagship",
    "badgeType": "b-gen",
    "price": 275000,
    "priceFormatted": "Rs 275,000",
    "priceUsd": 990,
    "img": "images/laptop-69-dell-xps-13-plus-9320-69.jpg",
    "condition": "Open Box / Brand New Condition",
    "warranty": "1 Year Local Warranty + 7 Days Checking",
    "useCases": [
      "creator",
      "programming",
      "office"
    ]
  }
];

if (typeof module !== 'undefined') module.exports = LAPTOPS_INVENTORY;
